export const transArray = [
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5466",
    TransDate: "2022-03-20 09:07:34",
    TransStatus: "Successfull",
    ParamCalled: "5061230110337531681",
    EndPointSource: "API Call",
    ResponseMessage: "Result Found",
    RespTime: "1.396112",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource: {
      platform: "Interswitch", status: "Successful", message: "Lookup is Successful", account: "0151551397", errors: null
    }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5467",
    TransDate: "2022-03-20 10:08:20",
    TransStatus: "Successfull",
    ParamCalled: "5199110753910725",
    EndPointSource: "API Call",
    ResponseMessage: "Result Found",
    RespTime: "2.086379",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource:
    {
      platform: "Interswitch",
      status: "Successful",
      message: "Lookup is Successful",
      account: "2038078295",
      errors: null
    }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5468",
    TransDate: "2022-03-22 07:26:13",
    TransStatus: "Not Successfull",
    ParamCalled: "5399834480743483",
    EndPointSource: "API Call",
    ResponseMessage: "Not Found",
    RespTime: "3.874269",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource: { platform: "Interswitch", status: "Failed", message: "Suspected Fraud", account: null, errors: [{ code: "01", message: "Suspected fraud" }] }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5469",
    TransDate: "2022-03-20 19:18:02",
    TransStatus: "Successfull",
    ParamCalled: "5199110729556941",
    EndPointSource: "API Call",
    ResponseMessage: "Result Found",
    RespTime: "2.633968",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource: { platform: "Interswitch", status: "Successful", message: "Lookup is Successful", account: "2069116386", errors: null }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5470",
    TransDate: "2022-03-22 16:57:50",
    TransStatus: "Successfull",
    ParamCalled: "5061041755903661921",
    EndPointSource: "API Call",
    ResponseMessage: "Result Found",
    RespTime: "1.392581",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource: { platform: "Interswitch", status: "Successful", message: "Lookup is Successful", account: "1387736531", errors: null }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5471",
    TransDate: "2022-03-21 13:09:35",
    TransStatus: "Successfull",
    ParamCalled: "5399831613839485",
    EndPointSource: "API Call",
    ResponseMessage: "Result Found",
    RespTime: "1.067066",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource: { platform: "Interswitch", status: "Successful", message: "Lookup is Successful", account: "223086556401005900", errors: null }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5472",
    TransDate: "2022-03-20 13:35:02",
    TransStatus: "Successfull",
    ParamCalled: "5399830242855086",
    EndPointSource: "API Call",
    ResponseMessage: "Result Found",
    RespTime: "1.086359",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource:
      { platform: "Interswitch", status: "Successful", message: "Lookup is Successful", account: "905050227701001300", errors: null }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5473",
    TransDate: "2022-03-20 10:52:31",
    TransStatus: "Not Successfull",
    ParamCalled: "4187451854394600",
    EndPointSource: "API Call",
    ResponseMessage: "Not Found",
    RespTime: "3.30342",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource:
    {
      platform: "Interswitch",
      status: "Failed",
      message: "Routing Error",
      account: null,
      errors: [{ code: "01", message: "Routing error" }]
    }

  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5474",
    TransDate: "2022-03-20 12:40:54",
    TransStatus: "Not Successfull",
    ParamCalled: "4187451835362817",
    EndPointSource: "API Call",
    ResponseMessage: "Not Found",
    RespTime: "3.840352",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource:
    {
      platform: "Interswitch",
      status: "Failed",
      message: "Routing error",
      account: null,
      errors: [{ code: "01", message: "Routing error" }]
    }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5475",
    TransDate: "2022-03-20 18:24:47",
    TransStatus: "Not Successfull",
    ParamCalled: "4920690015658955",
    EndPointSource: "API Call",
    ResponseMessage: "Not Found",
    RespTime: "24.702979",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource: { platform: "Interswitch", status: "Failed", message: "Routing Error", account: null, errors: [{ code: "01", message: "Routing error" }] }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5476",
    TransDate: "2022-03-21 07:50:06",
    TransStatus: "Successfull",
    ParamCalled: "5199110666970139",
    EndPointSource: "API Call",
    ResponseMessage: "Result Found",
    RespTime: "2.470451",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource: { platform: "Interswitch", status: "Successful", message: "Lookup is Successful", account: "2077284727", errors: null }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5477",
    TransDate: "2022-03-21 18:27:46",
    TransStatus: "Not Successfull",
    ParamCalled: "5399412278935981",
    EndPointSource: "API Call",
    ResponseMessage: "Not Found",
    RespTime: "8.478302",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource: { platform: "Interswitch", status: "Failed", message: "Issuer or switch inoperative", account: null, errors: [{ code: "01", message: "Issuer or switch inoperative" }] }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5478",
    TransDate: "2022-03-21 08:56:24",
    TransStatus: "Successfull",
    ParamCalled: "5199110785281285",
    EndPointSource: "API Call",
    ResponseMessage: "Result Found",
    RespTime: "2.721702",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource: { platform: "Interswitch", status: "Successful", message: "Lookup is Successful", account: "2188755804", errors: null }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "50",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5479",
    TransDate: "2022-03-22 03:37:48",
    TransStatus: "Successfull",
    ParamCalled: "5199110774528498",
    EndPointSource: "API Call",
    ResponseMessage: "Result Found",
    RespTime: "1.497797",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource: { platform: "Interswitch", status: "Successful", message: "Lookup is Successful", account: "2197377831", errors: null }
  },
  {
    fldemail: "dotuna@opay.team",
    serviceID: "808922",
    TransAmount: "0",
    TransType: "WithDrawal",
    TransSource: "CARDLookup API",
    ReferenceNo: "5480",
    TransDate: "2022-03-21 16:27:49",
    TransStatus: "Not Successfull",
    ParamCalled: "5061150705522888949",
    EndPointSource: "API Call",
    ResponseMessage: "Network Error",
    RespTime: "0",
    QuerySource: "Interswitch",
    data_point: null,
    headers: null,
    ResponseFromSource: { platform: "Interswitch", status: "Failed", message: "Network Error", account: null, errors: [{ code: "01", message: "Issuer or switch inoperative" }] }
  }
]